// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = 'https://brfzwofppdvyyrbscabs.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZnp3b2ZwcGR2eXlyYnNjYWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjMwMDgsImV4cCI6MjA2ODgzOTAwOH0.I0CecGd5brxTunBNsJTY4rcmPD8oROAx06CaHvEgplM';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);